### PR TITLE
feat: implement big emoji messages and optimize emoji filtering

### LINKED ISSUE #1409: Emoji Only Messages

### PR DESCRIPTION
**Pull request by lourou**
#### Message Bubbles
   - Add `transparent` and `noPadding` options to bubble components
   - Preserve original bubble styling and border radius logic
   - Add support for transparent backgrounds in big emoji messages

#### Emoji Detection
   - Switch to emoji-regex package for more accurate emoji detection
   - Fix emoji counting to properly handle combined emojis (ZWJ sequences)
   - Optimize `shouldRenderBigEmoji` function for better performance

#### Text Styling
   - Add and use design system's xxl text size for big emojis
   - Maintain consistent styling across regular and reply messages
   - Keep `ClickableText` functionality for message interactions

#### Reply Messages
   - Add big emoji support in reply messages
   - Maintain consistent styling with main messages
   - Preserve reply message reference functionality

Fixes #1409

## Summary by CodeRabbit

- **New Features**
	- Introduced a new text size option (`xxl`) in the design system for larger text display.
	- Updated message rendering logic to conditionally display a big emoji based on message content.

- **Bug Fixes**
	- Enhanced emoji rendering conditions to improve message display accuracy.

- **Documentation**
	- Updated documentation to reflect new text size and message rendering features.

### CODE REVIEW

**Comment by lourou** [comment]
+ performance update of the emoji picker by @thierryskoda 🫶

**Review by thierryskoda — COMMENTED** [review]
Some thoughts! Let me know if it makes sense, maybe not, but just a few thoughts to challenge the optional props and creating new components. https://www.loom.com/share/1a3683153c4140a9ac2f903f276fcac6

**Review by alexrisch — APPROVED** [review]

**Comment by alexrisch** [comment]
Approved! But I think we will get even better performance moving past the first character with https://github.com/ephemeraHQ/converse-app/pull/1431, so I can rebase after this gets merged

**Comment by lourou** [comment]
Changed made! I simplified and followed your recos @thierryskoda, thanks :)

**Review by thierryskoda — APPROVED** [review]

**Pull request merged**
