### PR TITLE
feat: Emoji Picker

### PR DESCRIPTION
**Pull request by alexrisch**
Updates to Emoji Picker
Handle Android
Added Drawer Component
Fixed iOS Jank
Fixed Android Reactions
Removed Vendor emoji picker
Set groundwork for Personalized emojis
Closes https://github.com/ephemeraHQ/converse-app/issues/556 
I believe closes https://github.com/ephemeraHQ/converse-app/issues/555
Closes https://github.com/ephemeraHQ/converse-app/issues/427

https://github.com/user-attachments/assets/0b4ee293-fbdf-48f0-b9ef-7e6b05daad51

Simulator Screenshot - iPhone 15 Pro - 2024-08-27 at 16 38 06

### CODE REVIEW

**Review by cameronvoell — APPROVED** [review]

**Comment by saulmc** [comment]
Wow, fast work on this. Some design feedback:

- The "Your Reactions" row suggests customization, but that can't be done yet. Think we should hide it for now.
- The spring in the drawer pan from 0:14-0:16 in the video is pretty intense. Or was that just how you were gesturing?
- The row that shows who placed each reaction is supposed to be anchored to the top of the screen (there's also some padding/margin issue around 0:04 in the video)
- Sizes and padding are all greater than as designed - you can get em from Zeplin here: https://zpl.io/NEwQN3v

Also, looks like the default profile photos aren't loading properly next to the emojis in the message bubble -- separate bug?

**Comment by alexrisch** [comment]
> Wow, fast work on this. Some design feedback:
> 
> * The "Your Reactions" row suggests customization, but that can't be done yet. Think we should hide it for now.
> * The spring in the drawer pan from 0:14-0:16 in the video is pretty intense. Or was that just how you were gesturing?
> * The row that shows who placed each reaction is supposed to be anchored to the top of the screen (there's also some padding/margin issue around 0:04 in the video)
> * Sizes and padding are all greater than as designed - you can get em from Zeplin here: https://zpl.io/NEwQN3v
> 
> Also, looks like the default profile photos aren't loading properly next to the emojis in the message bubble -- separate bug?

Thank you for the feedback!

I'll hide the "Your Reactions" as the customization portion is not completed yet

The spring was due to the emojis being filtered and reducing the size of the list, so I'll make it less intense

I'll make sure the margin matches both left & right and aligns on the top for the reactions bubble

The missing reactions might be due to the default profile picture being missing, I'll fix that up, but may do it in a separate PR instead to avoid adding more to this PR

The linked Zeplin is mostly just a static image, I would love to have the actual values for those as it will heavily reduce the amount of guess work that is needed, as my brain truthfully does not notice a difference one way or another

**Comment by saulmc** [comment]
@alexrisch Double click in Zeplin to get measurements and styles:
CleanShot 2024-08-28 at 09 27 35@2x

**Comment by saulmc** [comment]
Better screenshot
CleanShot 2024-08-28 at 09 28 27@2x

**Comment by alexrisch** [comment]
Fixed reactors https://github.com/ephemeraHQ/converse-app/pull/606

**Comment by alexrisch** [comment]
@saulmc I've made most of the updates I could, I'm still having issues getting all of the styles out of Zeplin but did my best to match those

**Comment by saulmc** [comment]
Thx @alexrisch ! I can go in and tweak anything that still needs it, but let's figure out a more lasting solution for getting styles out of Zeplin or Figma.

**Pull request merged**
