### PR TITLE
Clean up inline styles

### PR DESCRIPTION
**Pull request by alexrisch**
Removed a number of inline styles being used
Removed old group invites
Removed handling of old group invite link patter groupInvite, only group-invite will work now

### CODE REVIEW

**Comment by thierryskoda** [comment]
I have it on the agenda for Monday to discuss styling and what we want to do moving on. Would also want to discuss those refactoring/cleaning up PRs and what we want to do about them. Since we'll be a lot working on the app now we might have many conflicts with those kinds of PRs

**Comment by alexrisch** [comment]
@thierryskoda Yep agreed, I was trying to steer clear of most Onboarding components as I know you are making changes there

**Comment by thierryskoda** [comment]
@alexrisch Haven't approved or did anything with this yet because as we move to design system, we'll remove those styles anyway. So not sure if it's worth merging and have conflicts 😵

**Comment by alexrisch** [comment]
I'm fine to close this!

**Pull request closed without merging**
